### ISSUE TITLE
you are not logged in! please verify the capcha then press any key to continue... Error!!

### ISSUE THREAD

**Issue by khushi1503** [joeyism/linkedin_scraper#83]
Following is my code - 

```
from linkedin_scraper import Person, actions
from selenium import webdriver
driver = webdriver.Chrome('location of driver')

email = "username"
password = "password"
actions.login(driver, email, password)
person = Person("https://www.linkedin.com/in/khushi-thakkar-906b56188/", driver=driver)
person.scrape(close_on_complete=False)

print(person)
```

But I am constantly getting the following error (even though I have logged into linkedin) - 
you are not logged in!
please verify the capcha then press any key to continue...

**Comment by joeyism** [comment]
Add a break after `actions.login`, finish the captcha, then run the `scrape`

**Comment by khushi1503** [comment]
What is to be entered in the captcha? 
From where do we get it?

**Comment by joeyism** [comment]
You need to verify that you are not a bot by manually filling out [CAPTCHA](https://en.wikipedia.org/wiki/CAPTCHA). So when chrome starts up, you can manually enter the CAPTCHA code, and when you get to the main page, you can start the scraping process

**Comment by JulianAntonioMurillo** [comment]
Hi, I had a similar issue. It may be because you are running the scrape twice? When I run person = Person("https://www.linkedin.com/in/khushi-thakkar-906b56188/", driver=driver, close_on_complete = False) it scrapes the page without the Captcha error. If you're running that in addition to person.scrape(close_on_complete=False) Linkedin Will Prompt another login and you'll get a message saying "You're not logged-in! Complete Captcha challenge".
